# =============================================================================
# Jenkins Module — Main
#
# Provisions a fully automated Enterprise Jenkins cluster:
#   1 Master (Controller)  — serves the UI, orchestrates pipelines
#   1 build-agent          — Node.js 20, NPM, Git, kustomize
#   1 security-agent       — Docker (for Kaniko container), Trivy, AWS CLI
#   1 test-agent           — Docker, Newman, newman-reporter-junit, OWASP ZAP
#
# ZERO SSH KEY MANAGEMENT:
#   Terraform generates an ephemeral SSH key pair.
#   Private key is stored ONLY in AWS SSM Parameter Store (encrypted).
#   Agents auto-register themselves to the master via SSH on boot.
#   Users access the master via SSM Session Manager — no bastion host needed.
# =============================================================================

# ── Auto-resolve latest Amazon Linux 2023 AMI if not provided ────────────────
data "aws_ami" "amazon_linux_2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-2023.*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

locals {
  ami = var.ami_id != "" ? var.ami_id : data.aws_ami.amazon_linux_2023.id
  # Note: JCasC config is downloaded from GitHub at EC2 boot time (see [8/9] in user_data).
  # This keeps user_data under AWS's 16 KB limit.
}

# ── Generate SSH Key Pair for Agent-to-Master SSH connections ─────────────────
# No manual key pair creation or downloading of .pem files required.
resource "tls_private_key" "jenkins_agent_ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

# Store the private key in SSM (encrypted at rest with AWS KMS)
# Jenkins Master will read this from SSM to configure SSH credentials
resource "aws_ssm_parameter" "jenkins_ssh_private_key" {
  name        = "/${var.cluster_name}/jenkins/agent-ssh-private-key"
  description = "Jenkins agent SSH private key - used by Master to SSH into agents"
  type        = "SecureString"
  value       = tls_private_key.jenkins_agent_ssh.private_key_pem

  tags = {
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# ── Jenkins Admin Password — auto-generated, stored in SSM ───────────────────
resource "random_password" "jenkins_admin" {
  length           = 24
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_ssm_parameter" "jenkins_admin_password" {
  name        = "/${var.cluster_name}/jenkins/admin-password"
  description = "Jenkins admin user password — auto-generated by Terraform"
  type        = "SecureString"
  value       = random_password.jenkins_admin.result
  overwrite   = true

  tags = {
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# ── Security Group: Jenkins Master ────────────────────────────────────────────
resource "aws_security_group" "jenkins_master_sg" {
  name        = "${var.cluster_name}-jenkins-master-sg"
  description = "Jenkins Master Controller - allow UI (8080) and JNLP agent port (50000)"
  vpc_id      = var.vpc_id

  # Jenkins UI — restrict this to your office/VPN CIDR in production
  ingress {
    description = "Jenkins Web UI"
    from_port   = 8080
    to_port     = 8080
    protocol    = "tcp"
    cidr_blocks = var.allowed_cidr_blocks
  }

  # JNLP — agents connect inbound on this port
  ingress {
    description = "Jenkins JNLP Agent Port"
    from_port   = 50000
    to_port     = 50000
    protocol    = "tcp"
    # Only allow inbound JNLP from within the VPC (agents are in private subnets)
    cidr_blocks = ["10.0.0.0/8"]
  }

  # All outbound traffic allowed (for plugin downloads, GitHub, ECR)
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name        = "${var.cluster_name}-jenkins-master-sg"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# ── Security Group: All Jenkins Agents ───────────────────────────────────────
# Agents sit in private subnets. They only need:
#   - SSH from Master (port 22, restricted to master's SG)
#   - Outbound to master JNLP port and internet (ECR, GitHub)
resource "aws_security_group" "jenkins_agent_sg" {
  name        = "${var.cluster_name}-jenkins-agent-sg"
  description = "Jenkins Agent nodes - SSH from master only"
  vpc_id      = var.vpc_id

  ingress {
    description     = "SSH from Jenkins Master only"
    from_port       = 22
    to_port         = 22
    protocol        = "tcp"
    security_groups = [aws_security_group.jenkins_master_sg.id]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name        = "${var.cluster_name}-jenkins-agent-sg"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# ── Elastic IP for Jenkins Master ─────────────────────────────────────────────
# A static public IP so the UI URL never changes after reboots
resource "aws_eip" "jenkins_master_eip" {
  domain   = "vpc"
  instance = aws_instance.jenkins_master.id

  tags = {
    Name        = "${var.cluster_name}-jenkins-master-eip"
    Environment = var.environment
  }
}

# =============================================================================
# ── MASTER NODE ──────────────────────────────────────────────────────────────
#
# Bootstrap sequence (runs once at first boot via user_data):
#   [1/9] Install Java 17
#   [2/9] Install Jenkins
#   [3/9] Skip setup wizard
#   [4/9] Install plugins (JCasC, role-strategy, ssh-agents, sonar, git, etc.)
#   [5/9] Fetch all secrets from AWS SSM
#   [6/9] Write multiline secrets (SSH key, Cosign PEM) to files
#   [7/9] Write single-line secrets to /etc/sysconfig/jenkins (JCasC env vars)
#   [8/9] Write jenkins.yaml (JCasC) — embedded at apply time via local.casc_yaml
#   [9/9] Install kustomize and start Jenkins
# =============================================================================
resource "aws_instance" "jenkins_master" {
  ami                    = local.ami
  instance_type          = var.master_instance_type
  subnet_id              = var.public_subnet_id
  vpc_security_group_ids = [aws_security_group.jenkins_master_sg.id]
  iam_instance_profile   = var.master_instance_profile

  root_block_device {
    volume_size           = 30
    volume_type           = "gp3"
    encrypted             = true
    delete_on_termination = true
  }

  user_data = base64encode(<<-EOT
    #!/bin/bash
    set -euo pipefail
    exec > /var/log/jenkins-master-init.log 2>&1

    echo "======================================================"
    echo " Jenkins Master Bootstrap — $(date)"
    echo "======================================================"

    # ── [1/9] Install Java 17 ─────────────────────────────────────────────
    echo "[1/9] Installing Java 17..."
    dnf install java-17-amazon-corretto git wget unzip -y

    # ── [2/9] Install Jenkins ─────────────────────────────────────────────
    echo "[2/9] Installing Jenkins stable..."
    wget -O /etc/yum.repos.d/jenkins.repo \
      https://pkg.jenkins.io/redhat-stable/jenkins.repo
    rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    dnf install jenkins -y

    # ── [3/9] Skip Setup Wizard — JCasC handles everything ────────────────
    echo "[3/9] Disabling Jenkins setup wizard..."
    mkdir -p /var/lib/jenkins
    echo "2.0" > /var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion
    echo "2.0" > /var/lib/jenkins/jenkins.install.UpgradeWizard.state

    # ── [4/9] Install Required Plugins BEFORE First Start ─────────────────
    echo "[4/9] Installing Jenkins plugins (2-3 min)..."
    export JENKINS_HOME=/var/lib/jenkins
    /usr/bin/jenkins-plugin-cli \
      --plugins "configuration-as-code role-strategy ssh-agents git workflow-aggregator sonar plain-credentials ssh-credentials credentials" \
      && echo "  Plugins OK." \
      || echo "  WARNING: Some plugins failed - Jenkins will retry on startup."
    chown -R jenkins:jenkins /var/lib/jenkins/plugins 2>/dev/null || true

    # ── [5/9] Fetch Secrets from AWS SSM ──────────────────────────────────
    echo "[5/9] Fetching secrets from AWS SSM..."
    export AWS_DEFAULT_REGION="${var.aws_region}"

    get_ssm() {
      aws ssm get-parameter --name "$1" --with-decryption \
        --query "Parameter.Value" --output text 2>/dev/null \
        || echo "$${2:-PLACEHOLDER_NOT_SET}"
    }

    JENKINS_ADMIN_PASS=$(get_ssm "/${var.cluster_name}/jenkins/admin-password")
    JENKINS_SSH_KEY=$(get_ssm   "/${var.cluster_name}/jenkins/agent-ssh-private-key")
    ECR_REG=$(get_ssm           "/${var.cluster_name}/jenkins/ecr-registry")
    ECR_STAGE=$(get_ssm         "/${var.cluster_name}/jenkins/ecr-stage-repo")
    ECR_PROD=$(get_ssm          "/${var.cluster_name}/jenkins/ecr-prod-repo")
    SONAR_TOKEN=$(get_ssm "/${var.cluster_name}/jenkins/sonarcloud-token" "REPLACE_WITH_SONARCLOUD_TOKEN")
    GH_USER=$(get_ssm     "/${var.cluster_name}/jenkins/github-username"  "abhijitkadam1706")
    GH_PAT=$(get_ssm      "/${var.cluster_name}/jenkins/github-pat"       "REPLACE_WITH_GITHUB_PAT")
    JWT_SECRET=$(get_ssm  "/${var.cluster_name}/jenkins/test-jwt-secret"      "default-test-jwt-secret")
    MONGO_PASS=$(get_ssm  "/${var.cluster_name}/jenkins/test-mongo-password"  "default-test-mongo-pass")
    COSIGN_PASS=$(get_ssm "/${var.cluster_name}/jenkins/cosign-key-password"  "REPLACE_WITH_COSIGN_PASS")
    COSIGN_KEY=$(get_ssm  "/${var.cluster_name}/jenkins/cosign-private-key"   "")

    # ── [6/9] Write Multiline Secrets to Files ────────────────────────────
    echo "[6/9] Writing secrets to disk..."
    mkdir -p /var/lib/jenkins/.ssh
    # Use printf (NOT echo) — preserves newlines in the PEM key
    printf '%s' "$JENKINS_SSH_KEY" > /var/lib/jenkins/.ssh/agent_key
    chmod 600 /var/lib/jenkins/.ssh/agent_key
    chown -R jenkins:jenkins /var/lib/jenkins/.ssh

    if [ -n "$COSIGN_KEY" ] && [ "$COSIGN_KEY" != "PLACEHOLDER_NOT_SET" ]; then
      printf '%s' "$COSIGN_KEY" > /var/lib/jenkins/cosign-private-key.pem
      chmod 600 /var/lib/jenkins/cosign-private-key.pem
      chown jenkins:jenkins /var/lib/jenkins/cosign-private-key.pem
      echo "  Cosign key written."
    fi

    # ── [7/9] Write Jenkins Environment Variables (sysconfig) ─────────────
    # JCasC reads these via $${VAR_NAME} syntax in jenkins.yaml at startup.
    # Using printf to safely handle special characters in secret values.
    echo "[7/9] Writing Jenkins environment (sysconfig)..."
    {
      printf 'JENKINS_ADMIN_PASSWORD="%%s"\n' "$JENKINS_ADMIN_PASS"
      printf 'AWS_REGION="%%s"\n'             "${var.aws_region}"
      printf 'ECR_REGISTRY="%%s"\n'           "$ECR_REG"
      printf 'ECR_STAGE_REPO="%%s"\n'         "$ECR_STAGE"
      printf 'ECR_PROD_REPO="%%s"\n'          "$ECR_PROD"
      printf 'SONARCLOUD_TOKEN="%%s"\n'       "$SONAR_TOKEN"
      printf 'GITHUB_USERNAME="%%s"\n'        "$GH_USER"
      printf 'GITHUB_PAT="%%s"\n'             "$GH_PAT"
      printf 'TEST_JWT_SECRET="%%s"\n'        "$JWT_SECRET"
      printf 'TEST_MONGO_PASS="%%s"\n'        "$MONGO_PASS"
      printf 'COSIGN_KEY_PASSWORD="%%s"\n'    "$COSIGN_PASS"
      printf 'BUILD_AGENT_HOST="%%s"\n'       "${aws_instance.build_agent.private_ip}"
      printf 'SECURITY_AGENT_HOST="%%s"\n'    "${aws_instance.security_agent.private_ip}"
      printf 'TEST_AGENT_HOST="%%s"\n'        "${aws_instance.test_agent.private_ip}"
      printf 'SONAR_PROJECT="mern-auth"\n'
      printf 'SONAR_ORG="abhijitkadam1706"\n'
      printf 'GITOPS_REPO="https://github.com/abhijitkadam1706/DevOps-Competency-2.git"\n'
      printf 'CASC_JENKINS_CONFIG="/var/lib/jenkins/jenkins.yaml"\n'
    } > /etc/sysconfig/jenkins
    echo "  sysconfig written."

    # ── [8/9] Download JCasC Configuration from GitHub ──────────────────────────
    # Downloads jenkins-casc-config.yaml from the repo instead of embedding it.
    # This keeps user_data under the AWS 16 KB limit and means JCasC can be
    # updated in source control without rebuilding the EC2 instance.
    echo "[8/9] Downloading JCasC (jenkins.yaml) from GitHub..."
    CASC_URL="https://raw.githubusercontent.com/abhijitkadam1706/DevOps-Competency-2/main/jenkins/jenkins-casc-config.yaml"
    if [ -n "$GH_PAT" ] && [ "$GH_PAT" != "PLACEHOLDER_NOT_SET" ] && [ "$GH_PAT" != "REPLACE_WITH_GITHUB_PAT" ]; then
      curl -fsSL -H "Authorization: token $GH_PAT" "$CASC_URL" \
        -o /var/lib/jenkins/jenkins.yaml \
        && echo "  JCasC downloaded (authenticated)." \
        || { echo "  Auth download failed, trying public..."; curl -fsSL "$CASC_URL" -o /var/lib/jenkins/jenkins.yaml; }
    else
      curl -fsSL "$CASC_URL" -o /var/lib/jenkins/jenkins.yaml \
        && echo "  JCasC downloaded (public repo)."
    fi
    chown jenkins:jenkins /var/lib/jenkins/jenkins.yaml

    # ── [9/9] Install kustomize and start Jenkins ──────────────────────────
    echo "[9/9] Installing kustomize and starting Jenkins..."
    curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
    mv kustomize /usr/local/bin/
    chmod +x /usr/local/bin/kustomize

    chown -R jenkins:jenkins /var/lib/jenkins
    systemctl enable jenkins
    systemctl start jenkins

    echo "======================================================"
    echo " Bootstrap COMPLETE — $(date)"
    PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
    echo " UI  : http://$PUBLIC_IP:8080"
    echo " Pass: aws ssm get-parameter --name /${var.cluster_name}/jenkins/admin-password --with-decryption --query Parameter.Value --output text --region ${var.aws_region}"
    echo "======================================================"
  EOT
  )

  # Ensure SSM params and agent IPs exist before the master is created.
  # (user_data reads SSM params at first boot — they must already exist)
  depends_on = [
    aws_ssm_parameter.jenkins_admin_password,
    aws_ssm_parameter.jenkins_ssh_private_key,
    aws_instance.build_agent,
    aws_instance.security_agent,
    aws_instance.test_agent,
  ]

  tags = {
    Name        = "${var.cluster_name}-jenkins-master"
    Role        = "jenkins-master"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# ── BUILD AGENT ──────────────────────────────────────────────────────────────
# Stages: 1 (Checkout & Build), 2 (Lint & SAST), 7 (GitOps Commit)
# Tools: Java 17, Node.js 20, NPM, Git, kustomize, sonar-scanner
# ─────────────────────────────────────────────────────────────────────────────
resource "aws_instance" "build_agent" {
  ami                    = local.ami
  instance_type          = var.build_agent_instance_type
  subnet_id              = var.private_subnet_id
  vpc_security_group_ids = [aws_security_group.jenkins_agent_sg.id]
  iam_instance_profile   = var.build_agent_instance_profile

  root_block_device {
    volume_size           = 30
    volume_type           = "gp3"
    encrypted             = true
    delete_on_termination = true
  }

  user_data = base64encode(<<-EOT
    #!/bin/bash
    set -euo pipefail
    exec > /var/log/jenkins-build-agent-init.log 2>&1

    echo "=== Installing Java 17 and build tools ==="
    dnf install java-17-amazon-corretto git python3 -y

    echo "=== Installing Node.js 20 ==="
    curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
    dnf install nodejs -y

    echo "=== Installing kustomize ${var.kustomize_version} ==="
    curl -sSfL "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${var.kustomize_version}/kustomize_${var.kustomize_version}_linux_amd64.tar.gz" \
      | tar xz -C /usr/local/bin
    chmod +x /usr/local/bin/kustomize

    echo "=== Installing sonar-scanner ${var.sonar_scanner_version} ==="
    SONAR_VERSION="${var.sonar_scanner_version}"
    wget -q "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$${SONAR_VERSION}-linux.zip"
    dnf install unzip -y
    unzip -q "sonar-scanner-cli-$${SONAR_VERSION}-linux.zip" -d /opt/
    ln -sf "/opt/sonar-scanner-$${SONAR_VERSION}-linux/bin/sonar-scanner" /usr/local/bin/sonar-scanner
    rm "sonar-scanner-cli-$${SONAR_VERSION}-linux.zip"

    echo "=== Creating Jenkins agent user ==="
    useradd -m -s /bin/bash jenkins-agent
    mkdir -p /home/jenkins-agent/.ssh /home/jenkins-agent/workspace

    echo "=== Installing SSH public key for Master access ==="
    # Write public key without heredoc to avoid leading-space corruption from Terraform indentation
    printf '%s\n' '${tls_private_key.jenkins_agent_ssh.public_key_openssh}' \
      > /home/jenkins-agent/.ssh/authorized_keys
    chmod 700 /home/jenkins-agent/.ssh
    chmod 600 /home/jenkins-agent/.ssh/authorized_keys
    chown -R jenkins-agent:jenkins-agent /home/jenkins-agent

    echo "=== Build agent bootstrap complete — Label: build-agent ==="
  EOT
  )

  tags = {
    Name        = "${var.cluster_name}-jenkins-build-agent"
    Role        = "jenkins-build-agent"
    AgentLabel  = "build-agent"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# ── SECURITY AGENT ───────────────────────────────────────────────────────────
# Stages: 3 (Quality Gate), 4 (Kaniko Build + Trivy)
# Tools: Java 17, Docker (for Kaniko container), Trivy, AWS CLI v2
# NOTE: Docker runs Kaniko as a container — no --privileged, no socket needed
# ─────────────────────────────────────────────────────────────────────────────
resource "aws_instance" "security_agent" {
  ami                    = local.ami
  instance_type          = var.security_agent_instance_type
  subnet_id              = var.private_subnet_id
  vpc_security_group_ids = [aws_security_group.jenkins_agent_sg.id]
  iam_instance_profile   = var.security_agent_instance_profile

  root_block_device {
    volume_size           = 50  # Extra space for Docker image layers and Kaniko cache
    volume_type           = "gp3"
    encrypted             = true
    delete_on_termination = true
  }

  user_data = base64encode(<<-EOT
    #!/bin/bash
    set -euo pipefail
    exec > /var/log/jenkins-security-agent-init.log 2>&1

    echo "=== Installing Java 17, Docker, and Git ==="
    dnf install java-17-amazon-corretto docker git -y

    echo "=== Starting Docker service ==="
    systemctl start docker
    systemctl enable docker

    echo "=== Installing Trivy ${var.trivy_version} ==="
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
      | sh -s -- -b /usr/local/bin ${var.trivy_version}
    trivy --version

    echo "=== Installing Cosign ${var.cosign_version} ==="
    curl -sSfL "https://github.com/sigstore/cosign/releases/download/${var.cosign_version}/cosign-linux-amd64" \
      -o /usr/local/bin/cosign
    chmod +x /usr/local/bin/cosign
    cosign version

    echo "=== Creating Jenkins agent user ==="
    useradd -m -s /bin/bash jenkins-agent
    usermod -aG docker jenkins-agent   # Allow jenkins-agent to run Docker (for Kaniko)
    mkdir -p /home/jenkins-agent/.ssh /home/jenkins-agent/workspace

    echo "=== Installing SSH public key for Master access ==="
    printf '%s\n' '${tls_private_key.jenkins_agent_ssh.public_key_openssh}' \
      > /home/jenkins-agent/.ssh/authorized_keys
    chmod 700 /home/jenkins-agent/.ssh
    chmod 600 /home/jenkins-agent/.ssh/authorized_keys
    chown -R jenkins-agent:jenkins-agent /home/jenkins-agent

    echo "=== Security agent bootstrap complete — Label: security-agent ==="
  EOT
  )

  tags = {
    Name        = "${var.cluster_name}-jenkins-security-agent"
    Role        = "jenkins-security-agent"
    AgentLabel  = "security-agent"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# ── TEST AGENT ───────────────────────────────────────────────────────────────
# Stages: 5 (Integration Tests + DAST), 6 (DAST Quality Gate)
# Tools: Java 17, Docker (isolated test networks), Newman, newman-reporter-junit
# ─────────────────────────────────────────────────────────────────────────────
resource "aws_instance" "test_agent" {
  ami                    = local.ami
  instance_type          = var.test_agent_instance_type
  subnet_id              = var.private_subnet_id
  vpc_security_group_ids = [aws_security_group.jenkins_agent_sg.id]
  iam_instance_profile   = var.test_agent_instance_profile

  root_block_device {
    volume_size           = 40  # Extra space for Docker images during integration test
    volume_type           = "gp3"
    encrypted             = true
    delete_on_termination = true
  }

  user_data = base64encode(<<-EOT
    #!/bin/bash
    set -euo pipefail
    exec > /var/log/jenkins-test-agent-init.log 2>&1

    echo "=== Installing Java 17, Docker, Node.js, Git ==="
    dnf install java-17-amazon-corretto docker git -y
    curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
    dnf install nodejs -y

    echo "=== Starting Docker service ==="
    systemctl start docker
    systemctl enable docker

    echo "=== Installing Newman and JUnit reporter ==="
    npm install -g newman newman-reporter-htmlextra newman-reporter-junit

    echo "=== Creating Jenkins agent user ==="
    useradd -m -s /bin/bash jenkins-agent
    usermod -aG docker jenkins-agent
    mkdir -p /home/jenkins-agent/.ssh /home/jenkins-agent/workspace

    echo "=== Installing SSH public key for Master access ==="
    printf '%s\n' '${tls_private_key.jenkins_agent_ssh.public_key_openssh}' \
      > /home/jenkins-agent/.ssh/authorized_keys
    chmod 700 /home/jenkins-agent/.ssh
    chmod 600 /home/jenkins-agent/.ssh/authorized_keys
    chown -R jenkins-agent:jenkins-agent /home/jenkins-agent

    echo "=== Test agent bootstrap complete — Label: test-agent ==="
  EOT
  )

  tags = {
    Name        = "${var.cluster_name}-jenkins-test-agent"
    Role        = "jenkins-test-agent"
    AgentLabel  = "test-agent"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}
