# =============================================================================
# Jenkins Module — Main
#
# AWS DevOps Competency Controls:
#   PRIAC-001 (Templated Infrastructure Provisioning)
#   PRIAC-002 (Configuration Management via SSM + user_data)
#   PRCICD-002 (Build & Test — Jenkins master/agent architecture)
#   PRSEC-001 (DevSecOps — encrypted volumes, least-privilege IAM)
#
# Architecture:
#   1 Master (Controller)  — serves the UI, orchestrates pipelines
#   1 Build Agent          — Node.js 20, sonar-scanner, kustomize
#   1 Security Agent       — Docker (Kaniko), Trivy, Cosign
#   1 Test Agent           — Docker, Newman, OWASP ZAP
#
# Security:
#   - SSH key pair auto-generated by Terraform, stored in SSM (encrypted)
#   - Admin password auto-generated, stored in SSM (encrypted)
#   - Agents register to master via SSH — no JNLP tokens exposed
#   - All EBS volumes encrypted at rest (AWS Well-Architected: SEC-008)
#   - Access via SSM Session Manager — no bastion host needed
# =============================================================================

# ── Latest Amazon Linux 2023 AMI ─────────────────────────────────────────────
# Automatically resolves the most recent AL2023 x86_64 AMI from AWS.
# Falls back to a user-supplied AMI ID if var.ami_id is set.
data "aws_ami" "amazon_linux_2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-2023.*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

locals {
  ami = var.ami_id != "" ? var.ami_id : data.aws_ami.amazon_linux_2023.id
}

# ── SSH Key Pair — Agent-to-Master Connections ────────────────────────────────
# Terraform generates an ephemeral RSA 4096-bit key pair.
# The private key is stored ONLY in SSM Parameter Store (encrypted with KMS).
# Agents receive the public key via user_data at boot time.
resource "tls_private_key" "jenkins_agent_ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_ssm_parameter" "jenkins_ssh_private_key" {
  name        = "/${var.cluster_name}/jenkins/agent-ssh-private-key"
  description = "Jenkins agent SSH private key — used by Master to SSH into agents"
  type        = "SecureString"
  value       = tls_private_key.jenkins_agent_ssh.private_key_pem

  tags = {
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# ── Jenkins Admin Password — Auto-generated ──────────────────────────────────
resource "random_password" "jenkins_admin" {
  length           = 24
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_ssm_parameter" "jenkins_admin_password" {
  name        = "/${var.cluster_name}/jenkins/admin-password"
  description = "Jenkins admin password — auto-generated by Terraform"
  type        = "SecureString"
  value       = random_password.jenkins_admin.result
  overwrite   = true

  tags = {
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# ── Security Group: Jenkins Master ────────────────────────────────────────────
# Follows AWS Well-Architected SEC-005: restrict ingress to required ports only.
resource "aws_security_group" "jenkins_master_sg" {
  name        = "${var.cluster_name}-jenkins-master-sg"
  description = "Jenkins Master - allow UI (8080) and JNLP agent port (50000)"
  vpc_id      = var.vpc_id

  # Jenkins Web UI — restrict to office/VPN CIDR in production
  ingress {
    description = "Jenkins Web UI"
    from_port   = 8080
    to_port     = 8080
    protocol    = "tcp"
    cidr_blocks = var.allowed_cidr_blocks
  }

  # SSH from agents (for reverse SSH tunnel if needed)
  ingress {
    description = "SSH from VPC"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/8"]
  }

  # NOTE: JNLP port 50000 is NOT opened — agents connect via SSH (port 22).
  # If you switch to JNLP-based agents in the future, add a rule here.

  # Outbound: plugin downloads, GitHub, ECR, SSM endpoints
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name        = "${var.cluster_name}-jenkins-master-sg"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# ── Security Group: Jenkins Agents ────────────────────────────────────────────
# Agents sit in private subnets. Inbound SSH from Master only.
resource "aws_security_group" "jenkins_agent_sg" {
  name        = "${var.cluster_name}-jenkins-agent-sg"
  description = "Jenkins Agent nodes - SSH from master only"
  vpc_id      = var.vpc_id

  ingress {
    description     = "SSH from Jenkins Master"
    from_port       = 22
    to_port         = 22
    protocol        = "tcp"
    security_groups = [aws_security_group.jenkins_master_sg.id]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name        = "${var.cluster_name}-jenkins-agent-sg"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# ── Elastic IP: Jenkins Master ────────────────────────────────────────────────
# Static public IP so the Jenkins URL never changes after reboots.
resource "aws_eip" "jenkins_master_eip" {
  domain   = "vpc"
  instance = aws_instance.jenkins_master.id

  tags = {
    Name        = "${var.cluster_name}-jenkins-master-eip"
    Environment = var.environment
  }
}

# =============================================================================
# MASTER NODE
#
# Bootstrap sequence (runs once at first boot via user_data):
#   [1/7] Install Java 17 (Amazon Corretto)
#   [2/7] Install Jenkins LTS from official RPM repository
#   [3/7] Skip setup wizard, download 60+ plugins with full dependency tree
#   [4/7] Fetch SSH key from SSM, write to disk for agent connections
#   [5/7] Install kustomize for GitOps manifest patching
#   [6/7] Write Groovy init scripts to auto-configure security:
#         - Create admin user from SSM password (no setup wizard)
#         - Enable Matrix-based Authorization (no anonymous access)
#         - Set Jenkins URL from EC2 instance metadata (IMDSv2)
#         - Set master executors to 0 (builds run on agents only)
#         - Self-cleanup: init scripts delete themselves after first run
#   [7/7] Set ownership, start Jenkins, wait for boot
#
# After boot, the only manual steps are:
#   - Add SSH agents (build-agent, security-agent, test-agent)
#   - Configure SonarQube, GitHub, and ECR credentials
#   - Create the CI/CD pipeline job
#
# See docs/DEPLOYMENT_GUIDE.md for step-by-step instructions.
# =============================================================================
resource "aws_instance" "jenkins_master" {
  ami                         = local.ami
  instance_type               = var.master_instance_type
  subnet_id                   = var.public_subnet_id
  vpc_security_group_ids      = [aws_security_group.jenkins_master_sg.id]
  iam_instance_profile        = var.master_instance_profile
  associate_public_ip_address = true
  monitoring                  = true

  # SEC-003: Enforce IMDSv2 — prevents SSRF-based credential theft
  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required"
    http_put_response_hop_limit = 2
  }

  root_block_device {
    volume_size           = 30
    volume_type           = "gp3"
    encrypted             = true
    delete_on_termination = true
  }

  user_data = base64encode(<<-EOT
    #!/bin/bash
    set -euo pipefail
    exec > /var/log/jenkins-master-init.log 2>&1

    echo "======================================================"
    echo " Jenkins Master Bootstrap — $(date)"
    echo " Fixes: plugin deps, security, URL, executor count"
    echo "======================================================"

    # ── [1/7] Install Java 17 (Amazon Corretto) ─────────────────────────
    echo "[1/7] Installing Java 17..."
    dnf install java-17-amazon-corretto git wget unzip -y

    # ── [2/7] Install Jenkins LTS ────────────────────────────────────────
    echo "[2/7] Installing Jenkins LTS..."
    wget -O /etc/yum.repos.d/jenkins.repo \
      https://pkg.jenkins.io/redhat-stable/jenkins.repo
    rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    dnf install jenkins -y

    # ── [3/7] Skip Setup Wizard & Install Plugins ────────────────────────
    # Disable the first-run wizard so Jenkins starts clean.
    # Download essential plugins + ALL dependencies from the update center.
    echo "[3/7] Installing plugins (with all dependencies)..."
    mkdir -p /var/lib/jenkins
    echo "2.0" > /var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion
    echo "2.0" > /var/lib/jenkins/jenkins.install.UpgradeWizard.state

    PLUGIN_DIR="/var/lib/jenkins/plugins"
    BASE_URL="https://updates.jenkins.io/download/plugins"
    mkdir -p "$PLUGIN_DIR"

    install_plugin() {
      local name="$1"
      local url="$${BASE_URL}/$${name}/latest/$${name}.hpi"
      if curl -fsSL --max-time 60 --retry 3 -o "$${PLUGIN_DIR}/$${name}.jpi" "$url" 2>/dev/null; then
        echo "  [OK]  $name"
      else
        echo "  [SKIP] $name — will install via UI"
        rm -f "$${PLUGIN_DIR}/$${name}.jpi"
      fi
    }

    # ─────────────────────────────────────────────────────────────────────
    # FULL dependency tree — resolves all "Failed to load" errors
    # Previously missing: script-security, apache-httpcomponents-client,
    #   caffeine-api, trilead-api, mina-sshd-api, gson-api, asm-api,
    #   jaxb, pipeline-model-api, pipeline-model-extensions, etc.
    # ─────────────────────────────────────────────────────────────────────
    PLUGINS=(
      # ── Foundation layer (required by almost everything) ──
      script-security
      javax-activation-api javax-mail-api jaxb
      asm-api json-api json-path-api gson-api
      jackson2-api snakeyaml-api
      commons-lang3-api commons-text-api
      caffeine-api
      okhttp-api apache-httpcomponents-client-4-api apache-httpcomponents-client-5-api
      mina-sshd-api-common mina-sshd-api-core
      trilead-api
      instance-identity bouncycastle-api
      structs variant
      plugin-util-api

      # ── Jenkins UI framework ──
      ionicons-api jquery3-api bootstrap5-api font-awesome-api echarts-api

      # ── Credentials stack ──
      credentials plain-credentials ssh-credentials credentials-binding

      # ── Security (fixes "Jenkins is currently unsecured") ──
      matrix-auth role-strategy

      # ── SCM / Git (fixes "Failed to load SCM API Plugin") ──
      scm-api git-client git
      display-url-api mailer

      # ── Pipeline foundation ──
      workflow-step-api workflow-api workflow-support
      workflow-scm-step workflow-cps workflow-job
      workflow-basic-steps
      durable-task workflow-durable-task-step

      # ── Pipeline stages (fixes "Failed to load Pipeline Input Step") ──
      pipeline-model-api pipeline-model-extensions pipeline-model-definition
      pipeline-build-step pipeline-input-step pipeline-milestone-step
      pipeline-stage-step pipeline-stage-view pipeline-stage-tags-metadata
      pipeline-graph-analysis pipeline-groovy-lib
      pipeline-rest-api

      # ── Branch + multibranch ──
      branch-api workflow-multibranch cloudbees-folder
      workflow-aggregator

      # ── SSH agents (for SSH-based agent connections) ──
      ssh-slaves

      # ── Quality + security tools ──
      sonar
      token-macro build-timeout timestamper ws-cleanup
      checks-api junit

      # ── Misc required by above ──
      antisamy-markup-formatter
    )

    for plugin in "$${PLUGINS[@]}"; do
      install_plugin "$plugin"
    done

    # ── [4/7] Fetch SSH Key from SSM ─────────────────────────────────────
    # The SSH private key is used to configure agent connections in Jenkins UI.
    echo "[4/7] Fetching SSH key from SSM..."
    export AWS_DEFAULT_REGION="${var.aws_region}"

    JENKINS_SSH_KEY=$(aws ssm get-parameter \
      --name "/${var.cluster_name}/jenkins/agent-ssh-private-key" \
      --with-decryption --query "Parameter.Value" --output text 2>/dev/null || echo "")

    if [ -n "$JENKINS_SSH_KEY" ]; then
      mkdir -p /var/lib/jenkins/.ssh
      printf '%s' "$JENKINS_SSH_KEY" > /var/lib/jenkins/.ssh/agent_key
      chmod 600 /var/lib/jenkins/.ssh/agent_key
      echo "  SSH key written to /var/lib/jenkins/.ssh/agent_key"
    fi

    # ── [5/7] Install Kustomize ──────────────────────────────────────────
    echo "[5/7] Installing kustomize ${var.kustomize_version}..."
    curl -sSfL "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${var.kustomize_version}/kustomize_${var.kustomize_version}_linux_amd64.tar.gz" \
      | tar xz -C /usr/local/bin
    chmod +x /usr/local/bin/kustomize

    # ── [6/7] Groovy Init Scripts — Security & Configuration ─────────────
    # These run ONCE when Jenkins first starts, fixing all 4 UI warnings:
    #   1. "Jenkins is currently unsecured" → creates admin user + matrix auth
    #   2. "Jenkins URL is empty" → sets URL from EC2 instance metadata
    #   3. "Building on the built-in node" → sets executors to 0
    #   4. Plugin-related CSP/Java warnings → dismissable (no fix needed)
    echo "[6/7] Writing Groovy init scripts for security hardening..."
    INIT_DIR="/var/lib/jenkins/init.groovy.d"
    mkdir -p "$INIT_DIR"

    # Fetch the admin password from SSM for the admin user
    ADMIN_PASS=$(aws ssm get-parameter \
      --name "/${var.cluster_name}/jenkins/admin-password" \
      --with-decryption --query "Parameter.Value" --output text 2>/dev/null || echo "admin")

    # --- Groovy Script 1: Create Admin User & Enable Security ---
    # This fixes: "Jenkins is currently unsecured and allows anyone
    #              on the network to launch processes on your behalf"
    cat > "$INIT_DIR/01-security-setup.groovy" << 'GROOVYEOF'
import jenkins.model.*
import hudson.security.*
import org.jenkinsci.plugins.matrixauth.*

def jenkins = Jenkins.get()

// Check if security is already configured
if (jenkins.getSecurityRealm() instanceof HudsonPrivateSecurityRealm &&
    jenkins.getAuthorizationStrategy() instanceof ProjectMatrixAuthorizationStrategy) {
    println "[init] Security already configured — skipping"
    return
}

println "[init] Configuring Jenkins security..."

// Create the internal user database (no self-registration)
def realm = new HudsonPrivateSecurityRealm(false)
jenkins.setSecurityRealm(realm)

// Create admin user with password from SSM
def adminPass = new File('/var/lib/jenkins/secrets/.admin_pass').text.trim()
def admin = realm.createAccount("admin", adminPass)
admin.save()

// Set up Matrix-based Authorization
def strategy = new ProjectMatrixAuthorizationStrategy()
// Admin gets full access
strategy.add(Jenkins.ADMINISTER, "admin")
// Anonymous gets nothing (no read, no build, nothing)
jenkins.setAuthorizationStrategy(strategy)

jenkins.save()
println "[init] ✓ Security configured — admin user created, anonymous access disabled"
GROOVYEOF

    # Write the admin password to a temp file for the Groovy script
    mkdir -p /var/lib/jenkins/secrets
    printf '%s' "$ADMIN_PASS" > /var/lib/jenkins/secrets/.admin_pass
    chmod 600 /var/lib/jenkins/secrets/.admin_pass

    # --- Groovy Script 2: Set Jenkins URL ---
    # This fixes: "Jenkins URL is empty but is required for proper
    #              operation of many Jenkins features"
    cat > "$INIT_DIR/02-set-jenkins-url.groovy" << 'GROOVYEOF'
import jenkins.model.*

def jenkins = Jenkins.get()
def config = jenkins.getDescriptorByType(
    jenkins.model.JenkinsLocationConfiguration.class
)

// Use IMDSv2 to get the public IP of this EC2 instance
def token = ["curl", "-s", "-X", "PUT",
    "http://169.254.169.254/latest/api/token",
    "-H", "X-aws-ec2-metadata-token-ttl-seconds: 21600"
].execute().text.trim()

def publicIp = ["curl", "-s",
    "http://169.254.169.254/latest/meta-data/public-ipv4",
    "-H", "X-aws-ec2-metadata-token: $token"
].execute().text.trim()

if (publicIp && publicIp =~ /^\d+\.\d+\.\d+\.\d+$/) {
    def url = "http://$${publicIp}:8080/"
    config.setUrl(url)
    println "[init] ✓ Jenkins URL set to: $${url}"
} else {
    println "[init] WARNING: Could not detect public IP — set URL manually"
}
GROOVYEOF

    # --- Groovy Script 3: Set Master Executors to 0 ---
    # This fixes: "Building on the built-in node can be a security issue.
    #              You should set up distributed builds."
    cat > "$INIT_DIR/03-disable-built-in-executors.groovy" << 'GROOVYEOF'
import jenkins.model.*

def jenkins = Jenkins.get()

if (jenkins.getNumExecutors() != 0) {
    jenkins.setNumExecutors(0)
    jenkins.setMode(hudson.model.Node.Mode.EXCLUSIVE)
    jenkins.save()
    println "[init] ✓ Built-in node executors set to 0 (security best practice)"
} else {
    println "[init] Built-in node already has 0 executors — skipping"
}
GROOVYEOF

    # --- Groovy Script 4: Self-Cleanup ---
    # Remove init scripts after first run so they don't execute on every restart
    cat > "$INIT_DIR/99-cleanup.groovy" << 'GROOVYEOF'
import jenkins.model.*

def initDir = new File("/var/lib/jenkins/init.groovy.d")
def secretsFile = new File("/var/lib/jenkins/secrets/.admin_pass")

// Delete the admin password temp file
if (secretsFile.exists()) {
    secretsFile.delete()
    println "[init] ✓ Cleaned up admin password temp file"
}

// Delete all init scripts (they only need to run once)
initDir.listFiles()?.each { file ->
    if (file.name != "99-cleanup.groovy") {
        file.delete()
        println "[init] ✓ Removed init script: $${file.name}"
    }
}

// Delete cleanup script itself
new File("/var/lib/jenkins/init.groovy.d/99-cleanup.groovy").delete()
println "[init] ✓ All init scripts cleaned up — won't re-run on restart"
GROOVYEOF

    # ── [7/7] Set Ownership & Start Jenkins ──────────────────────────────
    echo "[7/7] Setting permissions and starting Jenkins..."
    chown -R jenkins:jenkins /var/lib/jenkins
    systemctl enable jenkins
    systemctl start jenkins

    # Wait for Jenkins to fully start before declaring success
    echo "Waiting for Jenkins to start..."
    for i in $(seq 1 60); do
      if curl -s -o /dev/null -w '%%{http_code}' http://localhost:8080/login 2>/dev/null | grep -qE '200|403'; then
        echo "Jenkins is up and responding."
        break
      fi
      sleep 5
    done

    echo "======================================================"
    echo " Bootstrap COMPLETE — $(date)"
    # Use IMDSv2 token to get public IP
    TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" || echo "")
    PUBLIC_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4 || echo "unknown")
    echo " UI  : http://$PUBLIC_IP:8080"
    echo " User: admin"
    echo " Pass: aws ssm get-parameter --name /${var.cluster_name}/jenkins/admin-password --with-decryption --query Parameter.Value --output text --region ${var.aws_region}"
    echo ""
    echo " Security fixes applied:"
    echo "   ✓ Admin user created with SSM password"
    echo "   ✓ Matrix-based authorization enabled"
    echo "   ✓ Anonymous access disabled"
    echo "   ✓ Jenkins URL auto-configured from EC2 metadata"
    echo "   ✓ Built-in node executors set to 0"
    echo "   ✓ All plugin dependencies installed"
    echo "======================================================"
  EOT
  )

  depends_on = [
    aws_ssm_parameter.jenkins_admin_password,
    aws_ssm_parameter.jenkins_ssh_private_key,
  ]

  tags = {
    Name        = "${var.cluster_name}-jenkins-master"
    Role        = "jenkins-master"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# =============================================================================
# BUILD AGENT
#
# Pipeline Stages: Checkout & Build, Lint & SAST, GitOps Commit
# Tools: Java 17, Node.js 20, NPM, Git, kustomize, sonar-scanner
# =============================================================================
resource "aws_instance" "build_agent" {
  ami                    = local.ami
  instance_type          = var.build_agent_instance_type
  subnet_id              = var.private_subnet_id
  vpc_security_group_ids = [aws_security_group.jenkins_agent_sg.id]
  iam_instance_profile   = var.build_agent_instance_profile
  monitoring             = true

  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required"
    http_put_response_hop_limit = 2
  }

  root_block_device {
    volume_size           = 30
    volume_type           = "gp3"
    encrypted             = true
    delete_on_termination = true
  }

  user_data = base64encode(<<-EOT
    #!/bin/bash
    set -euo pipefail
    exec > /var/log/jenkins-build-agent-init.log 2>&1

    echo "=== Build Agent Bootstrap — $(date) ==="

    echo "[1/5] Installing Java 17 and build tools..."
    dnf install java-17-amazon-corretto git python3 -y

    echo "[2/5] Installing Node.js 20..."
    curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
    dnf install nodejs -y

    echo "[3/5] Installing kustomize ${var.kustomize_version}..."
    curl -sSfL "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${var.kustomize_version}/kustomize_${var.kustomize_version}_linux_amd64.tar.gz" \
      | tar xz -C /usr/local/bin
    chmod +x /usr/local/bin/kustomize

    echo "[4/5] Installing sonar-scanner ${var.sonar_scanner_version}..."
    SONAR_VERSION="${var.sonar_scanner_version}"
    wget -q "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$${SONAR_VERSION}-linux.zip"
    dnf install unzip -y
    unzip -q "sonar-scanner-cli-$${SONAR_VERSION}-linux.zip" -d /opt/
    ln -sf "/opt/sonar-scanner-$${SONAR_VERSION}-linux/bin/sonar-scanner" /usr/local/bin/sonar-scanner
    rm "sonar-scanner-cli-$${SONAR_VERSION}-linux.zip"

    echo "[5/5] Creating jenkins-agent user with SSH access..."
    useradd -m -s /bin/bash jenkins-agent
    mkdir -p /home/jenkins-agent/.ssh /home/jenkins-agent/workspace
    printf '%s\n' '${tls_private_key.jenkins_agent_ssh.public_key_openssh}' \
      > /home/jenkins-agent/.ssh/authorized_keys
    chmod 700 /home/jenkins-agent/.ssh
    chmod 600 /home/jenkins-agent/.ssh/authorized_keys
    chown -R jenkins-agent:jenkins-agent /home/jenkins-agent

    echo "=== Build Agent Ready — Label: build-agent ==="
  EOT
  )

  tags = {
    Name        = "${var.cluster_name}-jenkins-build-agent"
    Role        = "jenkins-build-agent"
    AgentLabel  = "build-agent"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# =============================================================================
# SECURITY AGENT
#
# Pipeline Stages: Quality Gate, Container Build (Kaniko), Trivy Scan, Cosign
# Tools: Java 17, Docker (for Kaniko), Trivy, Cosign, AWS CLI v2
# =============================================================================
resource "aws_instance" "security_agent" {
  ami                    = local.ami
  instance_type          = var.security_agent_instance_type
  subnet_id              = var.private_subnet_id
  vpc_security_group_ids = [aws_security_group.jenkins_agent_sg.id]
  iam_instance_profile   = var.security_agent_instance_profile
  monitoring             = true

  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required"
    http_put_response_hop_limit = 2
  }

  root_block_device {
    volume_size           = 50
    volume_type           = "gp3"
    encrypted             = true
    delete_on_termination = true
  }

  user_data = base64encode(<<-EOT
    #!/bin/bash
    set -euo pipefail
    exec > /var/log/jenkins-security-agent-init.log 2>&1

    echo "=== Security Agent Bootstrap — $(date) ==="

    echo "[1/5] Installing Java 17, Docker, Git..."
    dnf install java-17-amazon-corretto docker git -y

    echo "[2/5] Starting Docker service..."
    systemctl start docker
    systemctl enable docker

    echo "[3/5] Installing Trivy ${var.trivy_version}..."
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
      | sh -s -- -b /usr/local/bin ${var.trivy_version}
    trivy --version

    echo "[4/5] Installing Cosign ${var.cosign_version}..."
    curl -sSfL "https://github.com/sigstore/cosign/releases/download/${var.cosign_version}/cosign-linux-amd64" \
      -o /usr/local/bin/cosign
    chmod +x /usr/local/bin/cosign
    cosign version

    echo "[5/5] Creating jenkins-agent user with SSH access..."
    useradd -m -s /bin/bash jenkins-agent
    usermod -aG docker jenkins-agent
    mkdir -p /home/jenkins-agent/.ssh /home/jenkins-agent/workspace
    printf '%s\n' '${tls_private_key.jenkins_agent_ssh.public_key_openssh}' \
      > /home/jenkins-agent/.ssh/authorized_keys
    chmod 700 /home/jenkins-agent/.ssh
    chmod 600 /home/jenkins-agent/.ssh/authorized_keys
    chown -R jenkins-agent:jenkins-agent /home/jenkins-agent

    echo "=== Security Agent Ready — Label: security-agent ==="
  EOT
  )

  tags = {
    Name        = "${var.cluster_name}-jenkins-security-agent"
    Role        = "jenkins-security-agent"
    AgentLabel  = "security-agent"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# =============================================================================
# TEST AGENT
#
# Pipeline Stages: Integration Tests, DAST (OWASP ZAP)
# Tools: Java 17, Docker, Node.js 20, Newman, newman-reporter-junit
# =============================================================================
resource "aws_instance" "test_agent" {
  ami                    = local.ami
  instance_type          = var.test_agent_instance_type
  subnet_id              = var.private_subnet_id
  vpc_security_group_ids = [aws_security_group.jenkins_agent_sg.id]
  iam_instance_profile   = var.test_agent_instance_profile
  monitoring             = true

  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required"
    http_put_response_hop_limit = 2
  }

  root_block_device {
    volume_size           = 40
    volume_type           = "gp3"
    encrypted             = true
    delete_on_termination = true
  }

  user_data = base64encode(<<-EOT
    #!/bin/bash
    set -euo pipefail
    exec > /var/log/jenkins-test-agent-init.log 2>&1

    echo "=== Test Agent Bootstrap — $(date) ==="

    echo "[1/4] Installing Java 17, Docker, Node.js, Git..."
    dnf install java-17-amazon-corretto docker git -y
    curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
    dnf install nodejs -y

    echo "[2/4] Starting Docker service..."
    systemctl start docker
    systemctl enable docker

    echo "[3/4] Installing Newman and reporters..."
    npm install -g newman newman-reporter-htmlextra newman-reporter-junit

    echo "[4/4] Creating jenkins-agent user with SSH access..."
    useradd -m -s /bin/bash jenkins-agent
    usermod -aG docker jenkins-agent
    mkdir -p /home/jenkins-agent/.ssh /home/jenkins-agent/workspace
    printf '%s\n' '${tls_private_key.jenkins_agent_ssh.public_key_openssh}' \
      > /home/jenkins-agent/.ssh/authorized_keys
    chmod 700 /home/jenkins-agent/.ssh
    chmod 600 /home/jenkins-agent/.ssh/authorized_keys
    chown -R jenkins-agent:jenkins-agent /home/jenkins-agent

    echo "=== Test Agent Ready — Label: test-agent ==="
  EOT
  )

  tags = {
    Name        = "${var.cluster_name}-jenkins-test-agent"
    Role        = "jenkins-test-agent"
    AgentLabel  = "test-agent"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}
