# =============================================================================
# Staging Environment — Root Module
# Same architecture as production but smaller, cheaper instances
# Deletion protection OFF — allows clean teardowns for testing
# Cost-optimized: SPOT instances, single DocumentDB, no WAF (no domain yet)
# =============================================================================
terraform {
  backend "s3" {
    # Replace 203848753188 with your 12-digit AWS Account ID
    # This bucket was created by running terraform/global/bootstrap.tf first
    bucket         = "mern-auth-terraform-state-203848753188"
    key            = "staging/terraform.tfstate"
    region         = "ap-southeast-1"
    dynamodb_table = "mern-auth-terraform-locks"
    encrypt        = true
  }
}

locals {
  cluster_name = "mern-auth-staging"
  environment  = "staging"
}

# ── VPC ──────────────────────────────────────────────────────────────────────
module "vpc" {
  source       = "../../modules/vpc"
  vpc_cidr     = var.vpc_cidr
  cluster_name = local.cluster_name
  environment  = local.environment
}

# ── EKS (SPOT instances for cost savings in staging) ─────────────────────────
module "eks" {
  source             = "../../modules/eks"
  cluster_name       = local.cluster_name
  kubernetes_version = var.kubernetes_version
  vpc_id             = module.vpc.vpc_id
  vpc_cidr           = module.vpc.vpc_cidr_block
  private_subnet_ids = module.vpc.private_subnet_ids
  desired_nodes      = var.desired_nodes
  min_nodes          = var.min_nodes
  max_nodes          = var.max_nodes
  instance_types     = var.instance_types
  capacity_type      = "SPOT"
  environment        = local.environment
}

# ── DocumentDB (single instance — cost saving for staging) ───────────────────
module "documentdb" {
  source                     = "../../modules/documentdb"
  cluster_identifier         = "${local.cluster_name}-docdb"
  vpc_id                     = module.vpc.vpc_id
  database_subnet_ids        = module.vpc.database_subnet_ids
  eks_node_security_group_id = module.eks.node_security_group_id
  instance_class             = var.docdb_instance_class
  instance_count             = 1
  backup_retention_days      = 7
  deletion_protection        = false
  environment                = local.environment
}

# ── ALB (domain_name is optional — leave blank if you don't have one yet) ────
module "alb" {
  source            = "../../modules/alb"
  cluster_name      = local.cluster_name
  vpc_id            = module.vpc.vpc_id
  vpc_cidr          = module.vpc.vpc_cidr_block
  public_subnet_ids = module.vpc.public_subnet_ids
  oidc_provider_arn = module.eks.oidc_provider_arn
  oidc_issuer_url   = module.eks.cluster_oidc_issuer_url
  # Leave domain_name empty — ALB DNS name is auto-generated by AWS for free
  domain_name       = var.base_domain != "" ? "staging.${var.base_domain}" : ""
  environment       = local.environment
}

# ── IAM (Jenkins EC2 role is created here — no manual steps needed) ──────────
module "iam" {
  source            = "../../modules/iam"
  cluster_name      = local.cluster_name
  oidc_provider_arn = module.eks.oidc_provider_arn
  oidc_issuer_url   = module.eks.cluster_oidc_issuer_url
  # ECR repos are shared — they live in the production environment state
  # For staging, we pass an empty list (Jenkins pushes to stage repo directly)
  ecr_repository_arns = []
  docdb_secret_arn    = module.documentdb.secret_arn
  environment         = local.environment

  service_accounts = {
    "mern-auth-app" = {
      namespace   = "mern-auth-staging"
      policy_json = jsonencode({
        Version = "2012-10-17"
        Statement = [{
          Effect   = "Allow"
          Action   = ["secretsmanager:GetSecretValue"]
          Resource = module.documentdb.secret_arn
        }]
      })
    }
  }
}

# ── Monitoring ────────────────────────────────────────────────────────────────
module "monitoring" {
  source           = "../../modules/monitoring"
  cluster_name     = local.cluster_name
  environment      = local.environment
  alert_email      = var.alert_email
  docdb_cluster_id = "${local.cluster_name}-docdb"
}
